version: '3'
services:
  parity:
    image: parity
    env_file:
     - ./.env
    command: ["--chain", "kovan", "--db-path", "/chain-data/", "--ui-interface", "0.0.0.0", "--ws-interface", "0.0.0.0", "--ws-origins", "all", "--jsonrpc-hosts", "all", "--unsafe-expose", "--jsonrpc-interface", "0.0.0.0", "--force-ui", "--min-peers", "10", "--max-peers", "15", "--cache-size", "2048", "-d", "/keys-store/", "--unlock", "${ETH_ADDRESS_UAV},${ETH_ADDRESS_ASP_TATARSTAN},${ETH_LIGHTHOUSE_ADDRESS},${ETH_ADDRESS_ASP_MARIY_EL},${ETH_ADDRESS_ASP_KIROV}", "--password", "/unlock_password.txt"]
    build:
      context: ./parity/
      args:
        ETH_PASSWORD: ${ETH_PASSWORD}
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8080:8080"
      - "8180:8180"
    restart: always
    volumes:
      - parity-db-kovan:/chain-data/
      - parity-keystore:/keys-store/
    networks:
      app_net:
        ipv4_address: 172.18.18.3 # Temp fix, since go-ipfs does not accept URL as an API argument
  ipfs:
    image: ipfs
    command: ["--enable-pubsub-experiment", "--writable", "--unrestricted-api"]
    build:
      context: ./go-ipfs/
    ports:
      - "4001:4001"
      - "5001:5001"
      - "7080:8080"
      - "7081:8081"
    restart: always
    networks:
      app_net:
        ipv4_address: 172.18.18.2 # Temp fix, since go-ipfs does not accept URL as an API argument
  robonomics-comm:
    image: robonomics-comm
    build:
      context: ./robonomics-comm/
    depends_on:
      - parity
      - ipfs
    networks:
      app_net:
        ipv4_address: 172.18.18.4 # Temp fix, since go-ipfs does not accept URL as an API argument
  distributed-sky:
    image: distributed-sky
    build:
      context: ./distributed-sky/
    depends_on:
      - parity
      - ipfs
    networks:
      app_net:
        ipv4_address: 172.18.18.5 # Temp fix, since go-ipfs does not accept URL as an API argument
  uav:
    image: distributed-sky
    command: ["roslaunch", "distributed_sky_uav", "confirmer_infrastructure.launch", "lighthouse_contract:=${LIGHTHOUSE_CONTRACT}", "eth_account_address:=${ETH_ADDRESS_UAV}"]
    depends_on:
      - parity
      - ipfs
    ports:
      - "3122:22"
    networks:
      app_net:
        ipv4_address: 172.18.18.6 # Temp fix, since go-ipfs does not accept URL as an API argument
  tatarstan-asp:
    image: distributed-sky
    command: ["roslaunch", "--master-logger-level=debug", "airspace_service_provider", "asp_infrastructure.launch", "lighthouse_contract:=${LIGHTHOUSE_CONTRACT}", "eth_account_address:=${ETH_ADDRESS_ASP_TATARSTAN}", "asp_registry_address:=${RUSSIA_REGION_CONTRACT}", "asp_manifest_address:=${TATARSTAN_ASP_CONTRACT}"]
    depends_on:
      - parity
      - ipfs
    ports:
      - "3222:22"
    networks:
      app_net:
        ipv4_address: 172.18.18.7 # Temp fix, since go-ipfs does not accept URL as an API argument
  lighthouse:
    image: robonomics-comm
    command: ["roslaunch", "robonomics_lighthouse", "lighthouse.launch", "lighthouse_contract:=${LIGHTHOUSE_CONTRACT}", "web3_http_provider:=http://parity:8545", "ipfs_http_provider:=http://172.18.18.2:5001", "eth_account_address:=${ETH_LIGHTHOUSE_ADDRESS}"]
    depends_on:
      - parity
      - ipfs
    ports:
      - "3322:22"
    networks:
      app_net:
        ipv4_address: 172.18.18.8 # Temp fix, since go-ipfs does not accept URL as an API argument
  mariy-el-asp:
    image: distributed-sky
    command: ["roslaunch", "--master-logger-level=debug", "airspace_service_provider", "asp_infrastructure.launch", "lighthouse_contract:=${LIGHTHOUSE_CONTRACT}", "eth_account_address:=${ETH_ADDRESS_ASP_MARIY_EL}", "asp_registry_address:=${RUSSIA_REGION_CONTRACT}", "asp_manifest_address:=${MARIY_EL_ASP_CONTRACT}"]
    depends_on:
      - parity
      - ipfs
    ports:
      - "3422:22"
    networks:
      app_net:
        ipv4_address: 172.18.18.9 # Temp fix, since go-ipfs does not accept URL as an API argument
  kirov-asp:
    image: distributed-sky
    command: ["roslaunch", "--master-logger-level=debug", "airspace_service_provider", "asp_infrastructure.launch", "lighthouse_contract:=${LIGHTHOUSE_CONTRACT}", "eth_account_address:=${ETH_ADDRESS_ASP_KIROV}", "asp_registry_address:=${RUSSIA_REGION_CONTRACT}", "asp_manifest_address:=${KIROV_ASP_CONTRACT}"]
    depends_on:
      - parity
      - ipfs
    ports:
      - "3522:22"
    networks:
      app_net:
        ipv4_address: 172.18.18.10 # Temp fix, since go-ipfs does not accept URL as an API argument
volumes:
  parity-db-kovan:
  parity-keystore:
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.18.0/24
