version: '3'
services:
  parity:
    image: parity
    env_file:
     - ./.env
    command: ["--chain", "kovan", "--db-path", "/chain-data/", "--ui-interface", "0.0.0.0", "--ws-interface", "0.0.0.0", "--ws-origins", "all", "--jsonrpc-hosts", "all", "--unsafe-expose", "--jsonrpc-interface", "0.0.0.0", "--force-ui", "--min-peers", "5", "--max-peers", "10", "--cache-size", "2048", "-d", "/keys-store/", "--unlock", "${ETH_ADDRESS_UAV},${ETH_ADDRESS_ASP_TATARSTAN}", "--password", "/unlock_password.txt"]
    build:
      context: ./parity/
      args:
        ETH_PASSWORD: ${ETH_PASSWORD}
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8080:8080"
      - "8180:8180"
    restart: always
    volumes:
      - parity-db-kovan:/chain-data/
      - parity-keystore:/keys-store/
    networks:
      app_net:
        ipv4_address: 172.18.18.3 # Temp fix, since go-ipfs does not accept URL as an API argument
  ipfs:
    image: ipfs
    command: ["--enable-pubsub-experiment", "--writable", "--unrestricted-api"]
    build:
      context: ./go-ipfs/
    ports:
      - "4001:4001"
      - "5001:5001"
      - "7080:8080"
      - "7081:8081"
    restart: always
    networks:
      app_net:
        ipv4_address: 172.18.18.2 # Temp fix, since go-ipfs does not accept URL as an API argument
  robonomics-comm:
    image: robonomics-comm
    build:
      context: ./robonomics-comm/
    depends_on:
      - parity
      - ipfs
    networks:
      app_net:
        ipv4_address: 172.18.18.4 # Temp fix, since go-ipfs does not accept URL as an API argument
  distributed-sky:
    image: distributed-sky
    build:
      context: ./distributed-sky/
    depends_on:
      - parity
      - ipfs
    networks:
      app_net:
        ipv4_address: 172.18.18.5 # Temp fix, since go-ipfs does not accept URL as an API argument
  uav:
    image: distributed-sky
    command: ["roslaunch", "--screen", "--master-logger-level=info", "-v", "distributed_sky_uav", "test_ask_send.launch"]
    ports:
      - "3122:22"
    networks:
      app_net:
        ipv4_address: 172.18.18.6 # Temp fix, since go-ipfs does not accept URL as an API argument
  tatarstan-asp:
    image: distributed-sky
    command: ["sleep", "100d"]
    ports:
      - "3222:22"
    networks:
      app_net:
        ipv4_address: 172.18.18.7 # Temp fix, since go-ipfs does not accept URL as an API argument
volumes:
  parity-db-kovan:
  parity-keystore:
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.18.0/24
